### PR TITLE
[#7] [feature] Implement Client Connection + state machine

### LINKED ISSUE #7: [feature] Implement Client Connection + state machine
[Importance:] Main
[Duration:] 2 Days

Classes & Methods

    ClientConnection

        enum State { READ_HEADERS, WRITE, CLOSE }

        void onReadable()

        void onWritable()

        void changeState(State)

        void close()

Behavior

    Start in READ_HEADERS.

    For now, read until \r\n\r\n → switch to WRITE with “hello”.

    After write finished → CLOSE.

Acceptance

    Integration: connect via nc, receive “hello”, socket closes.

    No crashes on partial reads or EAGAIN.

### PR DESCRIPTION
**Pull request by onlyHydra**
Closes #7

### CODE REVIEW

**Review by Lilly81324 — APPROVED** [review]
looks good

**Review by Lilly81324 — APPROVED** [review]

File: include/UniqueFD.h [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+------------------------------------------ */
+
+#ifndef UNIQUEFD_H
+#define UNIQUEFD_H
+
+#include <unistd.h>
+
+class UniqueFD
+{
+	int fd_;
```
Comment (Lilly81324) [inline include/UniqueFD.h]: Should be explicitely private or public

**Review by Lilly81324 — DISMISSED** [review]
please fix

**Review by velikov777 — APPROVED** [review]
