### PR TITLE
[#92] [feature] fix upload multipart

### LINKED ISSUE #92: [feature] fix upload multipart
[Importance:] Urgent • {P0} • [Duration:] 3 Days

Vlad does whatever

### PR DESCRIPTION
**Pull request by velikov777**
Closes #92

### CODE REVIEW

File: src/networking/ClientConnection.cpp [hunk 1]
```diff
@@ -648,160 +699,188 @@ bool ClientConnection::wantsRead()
...
-				delete body;
-				body = 0;
-			}
-			req.cleanupBodyFile();
-			ready_to_close = true;
-		}
-		return;
-	}
+    // 5) Drive the HTTP/CGI state machine
+    std::cerr << "[tick] dispatch state=" << (int)state << std::endl;
```
Comment (Lilly81324) [inline src/networking/ClientConnection.cpp:818]: I already dont like that we keep outputting regularly

File: src/networking/ClientConnection.cpp [hunk 2]
```diff
@@ -1014,68 +1094,91 @@ void ClientConnection::runPreflight()
...
-    if (hc.chunked) {
-        // Build your chunked reader
-        decideBodyReader(/* chunked */);
-
-        // Optional: if you have a plan/spill threshold tied to the cap, set it here.
-        // (No-op if you don't use 'plan'.)
-        // plan.max_body_bytes = max_body_bytes;
+    if (hc.chunked)
+    {
+        std::cerr << "[preflight] choose ChunkedReader\n";
```
Comment (Lilly81324) [inline src/networking/ClientConnection.cpp:1157]: Please remove debug output before merging

**Review by Lilly81324 — APPROVED** [review]
Please remove your debug output statements before pushing the final version.
Also, please stop changing the formatting partway through.
Just leave format of stuff that you arent changing majorly.

**Review by onlyHydra — APPROVED** [review]
